version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  elasticsearch_data_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=nzhuts
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:1.7
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data_dev:/usr/share/elasticsearch/data

  redis:
    image: redis:3.0

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
     - postgres
     - redis
    command: /app-celery.sh

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /app-celerybeat.sh
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - postgres
      - redis

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - POSTGRES_USER=nzhuts
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - elasticsearch
