FROM python:3.5
ENV PYTHONUNBUFFERED 1

COPY ./utility /os-requirements
RUN /bin/bash -c "apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive xargs -ta <(awk '/^\s*[^#]/' /os-requirements/requirements-jessie.apt) -r -- apt-get install -q -y \
    && rm -rf /var/lib/apt/lists/*"

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
