# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models


def populate_data(apps, schema_editor):
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    HomePage = apps.get_model('core.HomePage')
    HutIndexPage = apps.get_model('core.HutIndexPage')
    CampsiteIndexPage = apps.get_model('core.CampsiteIndexPage')

    homepage_content_type = ContentType.objects.get(model='homepage', app_label='core')
    hutindexpage_content_type = ContentType.objects.get(model='hutindexpage', app_label='core')
    campsiteindexpage_content_type = ContentType.objects.get(model='campsiteindexpage', app_label='core')
    site = Site.objects.first()

    # Create homepage and set it as default site home
    homepage = HomePage.objects.create(
        title="New Zealand Huts and Campsites",
        slug='nzhuts',
        content_type=homepage_content_type,
        path='00010002',
        depth=2,
        numchild=2,
        url_path='/nzhuts/'
    )

    site.root_page_id = homepage.id
    site.save()

    # Add Hut and Campsite index pages
    hut_index = HutIndexPage.objects.create(
        title="Huts",
        slug='huts',
        content_type=hutindexpage_content_type,
        path='000100020001',
        depth=3,
        numchild=0,
        url_path='/nzhuts/huts/'
    )
    campsite_index = CampsiteIndexPage.objects.create(
        title="Campsites",
        slug='campsites',
        content_type=campsiteindexpage_content_type,
        path='000100020002',
        depth=3,
        numchild=0,
        url_path='/nzhuts/campsites/'
    )


def reverse_func(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_func),
    ]
